config/routes.rb
TwilioSurveyor::Engine.routes.draw do
  resources :alerts

  controller :doc_stats do
    post "#{TwilioSurveyor::Doc.plural_name}/data/search/#{TwilioSurveyor::Organization.display_name}-stats/" => "doc_stats#index"
    post "#{TwilioSurveyor::Doc.plural_name}/#{TwilioSurveyor::Organization.display_name}-stats/data/search/" => "doc_stats#index"
    post "#{TwilioSurveyor::Doc.plural_name}/:id/#{TwilioSurveyor::Organization.display_name}-stats/"  => "doc_stats#show"
  end
end

TwilioSurveyorStats::Engine.routes.draw do

  # survey routes for override
  controller :survey do
    post :make_call 
    post :call_terminated
    post :recieve_call, defaults: { format: :xml }
  end

  controller :survey,  defaults: { format: :xml } do
    post :twilio_response
  end

end

app/models/twilio_surveyor/alert.rb
module TwilioSurveyor
  class Alert < ActiveRecord::Base
    belongs_to :page
    belongs_to :group

    def self.by_page_id page_id
       relation = where(page_id: page_id).order(id: :desc).limit(1)
       relation.first unless relation.nil?
    end

    def self.check_and_send_alert page
      alert = by_page_id(page.id)
      unless alert.nil?
        alert.send_alert if alert.need_to_send_alert?
      end
    end

    def doc
      page.doc unless page.nil?
    end

    def need_to_send_alert?
      page_stats = PageStats.new(page)
      if greater_than
        check_average = page_stats.average >= average
      else
        check_average = page_stats.average <= average
      end
      check_average && (page_stats.sigma <= sigma)
    end

    def send_alert
      if last_sent.nil? || ((Time.now - last_sent) > 1.day)
        send_texts
        send_emails
        self.last_sent = Time.now
        self.save
      end
    end

    def send_texts
      text_numbers.each do |number|
        CallManager.text(text_message, number, outgoing_number)
      end
    end
    
    def send_emails
      Rails.logger.debug "DEBUG SENDING EMAILS " + emails.to_s
      emails.each do |email|
        AlertMailer.alert_notification(email,self)
      end
    end

    def outgoing_number
      if group.nil? || group.outgoing_number.nil?
        TwilioSurveyor.config["caller_id"]
      else
        group.outgoing_number
      end
    end

  end
end

app/models/twilio_surveyor/answer_stats.rb
module TwilioSurveyor
  class AnswerStats
    include StatsCalculator
    
    attr_reader :answer, :organization

    def initialize(answer,organization = nil)
      @answer = answer
      @organization = organization
    end

    def page_stats
      @page_stats ||= get_page_stats
    end

    def difference
      @difference ||= calculate_difference
    end

    def sigma_difference
      @sigma_difference ||= calculate_sigma_difference
    end

    def score
      @score ||= calculate_score
    end

    def has_score?
      @answer.page_has_tag?("control")
    end

  private

    def get_page_stats
      if @answer.page_is_numeric?
        page_stats = PageStats.by_page_id_and_organization_id(@answer.page.id,organization_id)
      end    
    end

    def calculate_difference
      if @answer.page_is_numeric? && 
        !page_stats.nil? && 
        !page_stats.average.nil?
        (@answer.digits.to_f - page_stats.average).abs
      end
    end

    def calculate_sigma_difference
      if @answer.page_is_numeric? && 
        !page_stats.nil? && 
        !page_stats.sigma.nil? && 
        page_stats.sigma != 0

        difference.to_f/page_stats.sigma
      end
    end

    def calculate_score
      if @answer.page_is_numeric? && has_score?
        if @answer.page.correct_answer === @answer.digits
          1
        else
          0
        end
      end
    end

    def organization_id
      organization.id unless organization.nil?
    end
  end
end

app/models/twilio_surveyor/call_stats.rb
module TwilioSurveyor
  class CallStats < ActiveRecord::Base
    include StatsCalculator

    belongs_to :call
    attr_accessor :organization_only

    def self.by_call_id call_id
      self.by_call_id_and_organization_id(call_id,nil)
    end

    def self.by_call_id_and_organization_id call_id, organization_id
      where(call_id: call_id).where(organization_id: organization_id).last
    end

    def self.update_everything!(organization=nil)
      Call.all.each do |call|
        CallStats.update_stats call, organization
      end
    end

    def self.update_all_stats call
      (call = Call.find(call)) if call.class.name == "Fixnum"
 
      CallStats.update_stats call
      unless call.docs.blank?
        call.docs.each do |doc|
          DocStats.update_stats doc
          doc.pages.each{ |p| PageStats.update_stats(p) }
        end
      end

      UserStats.update_stats call.user unless call.user.nil?
      OrganizationStats.update_stats call.organization unless call.organization.nil?
      GroupStats.update_stats call.group unless call.group.nil?

      unless call.organization.nil?
        CallStats.update_stats call, call.organization
        unless call.docs.blank?
          call.docs.each do |doc|
            DocStats.update_stats doc,call.organization
            doc.pages.each{ |p| PageStats.update_stats(p,call.organization) }
          end
        end
      end
    end

    def self.update_stats call, organization = nil
      if organization.nil? || organization == call.organization
        (call = Call.find(call)) if call.class.name == "Fixnum"
        stats = CallStats.new
        stats.organization_only = !organization.nil?
        stats.call = call
        stats.average_difference = stats.calculate_average_difference
        stats.average_sigma_difference = stats.calculate_average_sigma_difference
        stats.average_score = stats.calculate_average_score
        stats if stats.save
      end
    end

    def self.total_duration(group_id=nil)
      self.duration_array(group_id).sum.to_f
    end

    def self.average_duration(group_id=nil)
      self.total_duration(group_id)/self.duration_array.length unless self.duration_array.blank?
    end

    def self.average_score
      array = Call.all.collect{ |call| CallStats.by_call_id(call.id).average_score }.compact
      array.sum.to_f/array.length if (!array.nil? && array.length > 0)    
    end

    def answer_stats_array
      @answer_stats_array || get_answer_stats_array
    end

    def calculate_average_difference
      attribute_average answer_stats_array, "difference"
    end

    def calculate_average_sigma_difference
      attribute_average answer_stats_array, "sigma_difference"
    end

    def calculate_average_score
      attribute_average answer_stats_array, "score"
    end

    def has_score?
      !average_score.nil?
    end

  private
    
    def self.duration_array(group_id=nil)
      Call.select(:duration).by_group_id(group_id).where.not(duration: nil).collect{ |c| c.duration.to_i }
    end
    
    def get_answer_stats_array
      org = call.organization if @organization_only
      call.gathers.collect { |answer| AnswerStats.new(answer,org) }
    end
  end
end

app/models/twilio_surveyor/doc_stats.rb
module TwilioSurveyor
  class DocStats < ActiveRecord::Base
    include StatsCalculator

    belongs_to :doc
    belongs_to :organization

    def self.all_by_doc_id doc_id
      self.all_by_doc_id_and_organization_id(doc_id,nil)
    end

    def self.all_by_doc_id_and_organization_id doc_id, organization_id
      where(doc_id: doc_id).where(organization_id: organization_id)
    end

    def self.by_doc_id doc_id
      self.by_doc_id_and_organization_id(doc_id,nil)
    end

    def self.by_doc_id_and_organization_id doc_id, organization_id
      self.all_by_doc_id_and_organization_id(doc_id,organization_id).last
    end

    def self.update_everything!(organization=nil)
      Doc.all.each do |doc|
        DocStats.update_stats doc, organization
      end
    end

    def self.update_stats doc, organization = nil
      (doc = Doc.find(doc)) if doc.class.name == "Fixnum"
      stats = DocStats.new
      stats.organization = organization
      stats.doc = doc
      stats.average_sigma = stats.calculate_average_sigma
      stats.average_reliability = stats.calculate_average_reliability
      stats if stats.save
    end

    def self.average_sigma
      array = Doc.all.collect{ |doc| ds = DocStats.by_doc_id(doc.id); ds.average_sigma unless ds.nil? }.compact
      array.sum.to_f/array.length if (!array.nil? && array.length > 0)
    end

    def self.average_reliability
      array = Doc.all.collect{ |doc| ds = DocStats.by_doc_id(doc.id); ds.average_reliability unless ds.nil?  }.compact
      array.sum.to_f/array.length if (!array.nil? && array.length > 0)    
    end

    def page_stats_array
      @page_stats_array ||= get_page_stats_array
    end

    def calculate_average_sigma
      attribute_average page_stats_array, "sigma"
    end

    def calculate_average_reliability
      attribute_average page_stats_array, "reliability"
    end

    def has_reliability?
      !average_reliability.nil?
    end

  private

    def get_page_stats_array
      doc.gathers.collect{ |page| PageStats.by_page_id_and_organization_id(page.id,organization_id) }
    end

    def organization_id
      organization.id unless organization.nil?
    end


  end
end 

app/models/twilio_surveyor/group_stats.rb
module TwilioSurveyor
  class GroupStats < ActiveRecord::Base
    include StatsCalculator

    belongs_to :group

    def self.by_group_id group_id
      where(group_id: group_id).last
    end

    def self.update_everything!
      Group.all.each do |group|
        GroupStats.update_stats group
      end
    end

    def self.update_stats group
      (group = Group.find(group)) if group.class.name == "Fixnum"
      stats = GroupStats.new
      stats.group = group
      stats.sigma_score = stats.calculate_sigma_score
      stats.reliability_score = stats.calculate_reliability_score
      stats.use_score = stats.calculate_use_score
      stats.rating = stats.calculate_rating
      stats.save
    end

    def doc_stats_array
      @doc_stats_array ||= get_doc_stats_array
    end

    def num_calls
      @num_calls ||= group.calls.count
    end

    def num_users
      @num_users ||= group.users.count
    end

  private

    def get_doc_stats_array
      group.docs.collect{ |doc| DocStats.by_doc_id(doc.id) } unless group.docs.nil?
    end

  end
end

app/models/twilio_surveyor/organization_stats.rb
module TwilioSurveyor
  class OrganizationStats < ActiveRecord::Base
    include StatsCalculator

    belongs_to :organization

    def self.by_organization_id organization_id
      where(organization_id: organization_id).last
    end

    def self.update_everything!
      Organization.all.each do |organization|
        OrganizationStats.update_stats organization
      end
    end

    def self.update_stats organization
      (organization = Organization.find(organization)) if organization.class.name == "Fixnum"
      stats = OrganizationStats.new
      stats.organization = organization
      stats.sigma_score = stats.calculate_sigma_score
      stats.reliability_score = stats.calculate_reliability_score
      stats.use_score = stats.calculate_use_score
      stats.rating = stats.calculate_rating
      stats.save
    end

    def doc_stats_array
      @doc_stats_array ||= get_doc_stats_array
    end

    def num_calls
      @num_calls ||= organization.calls.count
    end

    def num_users
      @num_users ||= organization.users.count
    end

  private

    def get_doc_stats_array
      organization.group_docs.collect{ |doc| DocStats.by_doc_id(doc.id) } unless organization.group_docs.nil?
    end

  end
end

app/models/twilio_surveyor/page_stats.rb
module TwilioSurveyor
  class PageStats < ActiveRecord::Base
    include StatsCalculator

    belongs_to :page
    belongs_to :organization

    def self.by_page_id page_id
      self.by_page_id_and_organization_id(page_id,nil)
    end

    def self.by_page_id_and_organization_id page_id, organization_id
      where(page_id: page_id).where(organization_id: organization_id).last
    end

    def self.update_everything!(organization=nil)
      Page.all.each do |page|
        PageStats.update_stats page, organization
      end
    end

    def self.update_stats page, organization = nil
      (page = Page.find(page)) if page.class.name == "Fixnum"
      stats = PageStats.new
      stats.organization = organization
      stats.page = page
      stats.average = stats.calculate_average
      stats.save
      stats.sigma = stats.calculate_sigma
      stats.reliability = stats.calculate_reliability
      stats if stats.save
    end

    def calculate_average
      if page.is_numeric?
        digits = page.answers_by_organization_id(organization_id).collect{ |answers| answers.digits.to_f }
        digits.sum.to_f/digits.length
      end
    end

    def calculate_sigma
      if page.is_numeric?
        diffs_to_sigma answer_stats_array.collect{ |answer_stats| answer_stats.difference.to_f }
      end
    end

    def calculate_reliability
      if page.is_numeric? && page.has_tag?("control")
        unless page.correct_answer.nil? || page.correct_answer < 0
          attribute_average answer_stats_array, "score"
        end
      end
    end

    def answer_stats_array
      @answer_stats_array ||= get_answer_stats_array
    end

    def answer_occurrences answer_digits
      if page.is_numeric?
        page.answers.pluck(:digits).count(answer_digits.to_s)
      end
    end

    def occurrence_array options=nil
      if page.is_numeric?
        options = (0..9) if options.nil?
        options.collect{ |option| answer_occurrences(option) }
      end
    end

    def average_array options=nil
      if page.is_numeric?
        options = (0..9) if options.nil?
        options.collect{ |option| { xval: option, yval: (answer_occurrences(option).to_f/page.answers.count) } }
      end
    end

    def lg_array options=nil
      if page.is_numeric?
        options = (0..9) if options.nil?
        options.collect{ |option| { xval: option, yval: (answer_occurrences(option)) } }
      end
    end

    def duration_array
      page.answers.collect.with_index do |answer,index|
        { xval: index, yval: answer.recording_duration }
      end
    end

  private

    def get_answer_stats_array
      if page.is_numeric? 
        page.answers_by_organization_id(organization_id).collect { |answer| AnswerStats.new(answer,organization) }
      end
    end

    def organization_id
      organization.id unless organization.nil?
    end

  end
end 

app/controllers/twilio_surveyor/alerts_controller.rb
require_dependency "twilio_surveyor_stats/application_controller"

module TwilioSurveyor
  class AlertsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_alert, only: [:show, :edit, :update, :destroy]

    # GET /alerts
    def index
      @alerts = Alert.all
    end

    # GET /alerts/new
    def new
      @alert = Alert.new
    end

    # GET /alerts/1/edit
    def edit
    end

    # POST /alerts
    def create
      @alert = Alert.new(alert_params)
      if @alert.save
        redirect_to @alert, notice: 'Alert was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /alerts/1
    def update
      if @alert.update_attributes(alert_params)
        redirect_to @alert, notice: 'Alert was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /alerts/1
    def destroy
      @alert.destroy
      redirect_to alerts_url, notice: 'Alert was successfully destroyed.'
    end

  private

    def set_alert
      @alert = Alert.find(params[:id])
    end

    def alert_params
      params.require(:alert).permit(
        :id,  :_destroy,
        :page_id,
        :greater_than,
        :average,
        :sigma,
        :text_message
      ).tap do |whitelisted| 
        text_numbers = params[:alert][:text_numbers]
        whitelisted[:text_numbers] = to_array(params[:alert][:text_numbers])
        whitelisted[:emails] =  to_array(params[:alert][:emails])
      end
    end

    def to_array array_string
      array_string.gsub(" ","")[1..(array_string.length-2)].split(",")
    end
  end
end

app/controllers/twilio_surveyor/doc_stats_controller.rb
require_dependency "twilio_surveyor_stats/application_controller"

module TwilioSurveyor
  class DocStatsController < TwilioSurveyor::DocsController
    before_action :authenticate_admin!
    before_action :set_stats_for_organization, only: [:show, :index]

    def index
      super
      render template: 'twilio_surveyor/docs/index'
    end

    def show
      super
      render template: 'twilio_surveyor/docs/show'
    end

  private

    def set_stats_for_organization
      @stats_for_organization_id = params[:stats_for_organization_id]
    end
  end
end

app/views/twilio_surveyor/admin/_activity_box.html.haml
.info
  .span Activity

.data.left.wide
  %span.key number of #{TwilioSurveyor::Call.plural_name}
  %span.value= @system_report[:total_calls]
.data.left.wide
  %span.key total #{TwilioSurveyor::Call.display_name} duration
  %span.value= @system_report[:total_call_duration]
.data.left.wide
  %span.key average #{TwilioSurveyor::Call.display_name} duration
  %span.value= number_with_precision(@system_report[:avg_call_duration],precision: 2)
.data.left.wide
  %span.key total recording length
  %span.value= @system_report[:total_recording_duration]
.data.left.wide
  %span.key average per #{TwilioSurveyor::Call.display_name}
  %span.value= number_with_precision(@system_report[:avg_recording_duration],precision: 2)

app/views/twilio_surveyor/admin/_scores_box.html.haml
.info
  .span Scores
.data.wide.left
  %span.key number of #{TwilioSurveyor::User.plural_name}
  %span.value= @system_report[:total_users]
.data.wide.left
  %span.key number of #{TwilioSurveyor::Doc.plural_name}
  %span.value= @system_report[:total_docs]
.data.wide.left
  %span.key number #{TwilioSurveyor::Group.plural_name}
  %span.value= @system_report[:total_groups]

app/views/twilio_surveyor/admin/_summary_box.html.haml
.info
  .span Summary
.data.wide.left
  %span.key number of #{TwilioSurveyor::User.plural_name}
  %span.value= @system_report[:total_users]
.data.wide.left
  %span.key number of #{TwilioSurveyor::Doc.plural_name}
  %span.value= @system_report[:total_docs]
.data.wide.left
  %span.key number #{TwilioSurveyor::Group.plural_name}
  %span.value= @system_report[:total_groups]

app/views/twilio_surveyor/admin/call_number.html.haml
- selector_options = options_for_select([TwilioSurveyor::Group.display_name,TwilioSurveyor::Organization.display_name])
- group_options = options_from_class(TwilioSurveyor::Group,nil,"outside_number")
- organization_options = options_from_class(TwilioSurveyor::Organization,nil,"outside_number")
- doc_options = options_from_class(TwilioSurveyor::Doc)

- if TwilioSurveyor.config['trigger'].blank? || TwilioSurveyor.config['trigger']['from_map'].blank?
  - call_number_name = "From"
  - group_or_organization_number_name = "To"
- else 
  - call_number_name =  TwilioSurveyor.config['trigger']['from_map']
  - group_or_organization_number_name =  TwilioSurveyor.config['trigger']['to_map']



%h1 Twilio Surveyor Demo
%h2{:style => "color: #ff0000"}= params['msg']
%h2 This form triggers a call as if it where an outside trigger (such as a missed call system).


%h3 Enter a number and select a *doc.

%form{action: zdial_call_path, method: :post}
  .form-section
    #{label_tag "number"}:
    %input{name: call_number_name, type: "text"}/

  .form-section.submission-selector{ data: { submission_name: "#{group_or_organization_number_name}" } }
    #{label_tag("registration_type")}:
    = select_tag("registration_type",selector_options,class: "selector")

    %div{ class: "selection #{TwilioSurveyor::Group.display_name} selected" }
      #{label_tag TwilioSurveyor::Group.display_name}:
      = select_tag(group_or_organization_number_name,group_options)

    %div{ class: "selection #{TwilioSurveyor::Organization.display_name}" }
      #{label_tag TwilioSurveyor::Organization.display_name}:
      = select_tag(nil,organization_options)

  .form-section
    #{label_tag TwilioSurveyor::Doc.display_name}:
    = select_tag("doc",doc_options)

  - unless TwilioSurveyor.config['trigger'].blank? || TwilioSurveyor.config['trigger']['access_key'].blank? 
    = hidden_field_tag(TwilioSurveyor.config['trigger']['access_key_map'],nil,value:TwilioSurveyor.config['trigger']['access_key'])
    = hidden_field_tag(TwilioSurveyor.config['trigger']['id_map'],nil,value:TwilioSurveyor.config['trigger']['id'])

  .form-submit 
    %input{:type => "submit", :value => "Call User"}/

%br
.div *If the user is not registerd they will be registered instead.

app/views/twilio_surveyor/admin/index.html.haml
%h1 Dashboard
.split-boxes.clearfix
  .right-box.content-box
  .left-box.content-box
    = render 'summary_box'
    %br
    = render 'activity_box'

- unless @last_call.nil?
  %h1 Latest #{TwilioSurveyor::Call.display_name} ( #{link_to @last_call.id.to_s, call_path(@last_call) } )
  = render 'twilio_surveyor/calls/show', call: @last_call